CREATE TABLE ENEMIES (
        ID serial,
        ENEMY_NAME VARCHAR(255) NOT NULL,
        HEALTH INT NOT NULL,
        ATTACK INT NOT NULL,
        DEFENSE INT NOT NULL,
        EXP INT NOT NULL,
        LVL INT NOT NULL
    );