CREATE TABLE CHARACTERS (
    ID serial PRIMARY KEY,
    USER_ID INT NOT NULL,
    CHARACTER_NAME VARCHAR(255) NOT NULL,
    CLASS_ID VARCHAR(255) NOT NULL,
    HEALTH INT NOT NULL,
    ATTACK INT NOT NULL,
    DEFENSE INT NOT NULL,
    EXP INT NOT NULL,
    LVL INT NOT NULL,
    GOLD INT NOT NULL
);