CREATE TABLE CHARACTER_ACHIEVEMENTS (
    ID serial PRIMARY KEY,
    USER_ID INT,
    CHARACTER_ID INT,
    ACHIEVEMENT_NAME VARCHAR(255),
    ACHIEVEMENT_DESCRIPTION VARCHAR(255),
    ACHIEVEMENT_SCORE INT
);