CREATE TABLE CHARACTER_SKILLS (
    ID serial PRIMARY KEY,
    USER_ID INT,
    CHARACTER_ID INT,
    SKILL_NAME VARCHAR(255),
    SKILL_DESCRIPTION VARCHAR(1000),
    SKILL_TYPE VARCHAR(255),
    LEVEL_REQUIREMENT INT,
    CLASS_REQUIREMENT INT,
    BASE_DAMAGE INT,
    BUFF INT
);