INSERT INTO USERS (USERNAME, PASSWORD) VALUES (
    'Stefischer',
    '1234'
);

INSERT INTO CHARACTERS (USER_ID, CHARACTER_NAME, CLASS_ID, HEALTH, ATTACK, DEFENSE, EXP, LVL, GOLD) VALUES (
1,
'Revenant',
1,
100,
12,
12,
0,
1,
100
);