INSERT INTO USERS (USER_NAME, PASSWORD) VALUES (
'Stefischer',
'1234'
);

INSERT INTO CHARACTERS (USER_ID, CHARACTER_NAME, CLASS_ID, HEALTH, ATTACK, DEFENSE, GOLD) VALUES (
1,
'Revenant',
1,
100,
12,
10,
100
);

INSERT INTO ITEMS (ITEM_NAME, ITEM_TYPE, WORTH) VALUES (
'Greatsword of Disease',
'Weapon',
80
);